### ISSUE TITLE
很漂亮的导航页

### ISSUE THREAD

**Issue by bfhh521** [eehhh/naviii#1]
您好，我使用Vercel进行了部署，在线编辑书签的时候会提示"保存失败"，我该怎么解决呢？

另外您会考虑给这个导航页增加一个验证吗？

**Comment by 2809728882** [comment]
后期会考虑，这个较容易实现，可以加我qq2809728882



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年6月10日(星期六) 下午3:01
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [eehhh/naviii] 很漂亮的导航页 (Issue #1)





 
您好，我使用Vercel进行了部署，在线编辑书签的时候会提示"保存失败"，我该怎么解决呢？
 
另外您会考虑给这个导航页增加一个验证吗？

**Comment by eehhh** [comment]
> 您好，我使用Vercel进行了部署，在线编辑书签的时候会提示"保存失败"，我该怎么解决呢？

可能是JSON格式的问题 可以找个JSON解析网站校验一下书签内容

> 另外您会考虑给这个导航页增加一个验证吗？

想增加一个什么样的验证呢

**Comment by bfhh521** [comment]
>可能是JSON格式的问题 可以找个JSON解析网站校验一下书签内容

是的，经过校验是JSON输入的格式问题

>想增加一个什么样的验证呢

希望能够在使用导航页之前，能增加一个简单的验证功能。
1. 因为使用导航页除了会添加公开的网站外，还会放置一些个人搭设的服务，验证功能可以帮助避免直接暴露自己的地址以及端口。
2. 我想到的是类似这样的验证，https://cloud.benym.cn/gpt/? 
3. 部分源码好像是在这里，https://github.com/Chanzhaoyu/chatgpt-web/blob/bc390ef09deb391c8d3f5a16aa9c45cc44082818/src/views/chat/layout/Permission.vue
供您参考，谢谢回复。

**Comment by eehhh** [comment]
> 希望能够在使用导航页之前，能增加一个简单的验证功能。

本项目没有后端 只在前端做验证很容易被绕过

> 2\. 我想到的是类似这样的验证，https://cloud.benym.cn/gpt/?
> 3\. 部分源码好像是在这里，https://github.com/Chanzhaoyu/chatgpt-web/blob/bc390ef09deb391c8d3f5a16aa9c45cc44082818/src/views/chat/layout/Permission.vue
>     供您参考，谢谢回复。

看了下你发的两个项目 都需要搭配后端做验证

**Comment by bfhh521** [comment]
原来如此，学习到了，谢谢您的回复。
